export interface Sale {
    id: number,
    status: "pending"|"inProgress"|"ended",
    tokenaddr: string,
    name: string,
    symbol: string,
    decimal: number,
    totalSupply: number,
    typeOfSale: "OpenForAll"|"OnlyWhiteListed"|"OnlyTokenHolders",
    criteriaToken: string,
    tokensForSale: number,
    liquidity: string,
    totalTokens: number,
    price: number,
    softCap:number,
    minimumTokens: string,
    minimumReq: number,
    maximumReq: number,
    startTime: string,
    endingTime: string,
    image: string,
    descriotion: string,
    webLink: string,
    telegramLink: string,
    twitterLink: string
}